name: Classroom
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  APP_PATH: /home/${{ secrets.SSH_USER_NAME }}/lab4

  ASPNETCORE_ENVIRONMENT: Development
  BUILD_CONFIGURATION: Debug
  GATEWAY_PORT: ${{ vars.GATEWAY_PORT }}
  LIBRARY_PORT: ${{ vars.LIBRARY_PORT }}
  RATING_PORT: ${{ vars.RATING_PORT }}
  RESERVATION_PORT: ${{ vars.RESERVATION_PORT }}

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker compose build
        docker compose push

  Deploy:
    needs: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clear app directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
            rm -rf ${{ env.APP_PATH }}
            mkdir -p ${{ env.APP_PATH }}

    - name: Copy helm files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASS }}
        port: 22
        source: ./k8s
        target: ${{ env.APP_PATH }}

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
            cd ${{ env.APP_PATH }}/k8s/
            helm upgrade postgres postgres-chart
            helm upgrade redis oci://registry-1.docker.io/bitnamicharts/redis -f redis-chart/values.yaml
            helm upgrade rsoi services

  Autograding:
    needs: Deploy
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true