version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 8000:5432
    networks:
      - db-local

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=redis_pass
    ports:
      - 8001:6379
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - redis-data

networks:
  db-local:
    driver: bridge
  redis-local:

volumes:
  db-data:
  redis-data: