version: "3"
services:
  person-service:
    image: ilyxabanchichi/rsoi-lab1-app:latest
    restart: always
    build:
      context: ./App/
      dockerfile: ./Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=persons;Username=program;Password=test
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 8090:5432

volumes:
  db-data:
